name: Build and Push to Docker Hub

on:
  push:
    paths:
      - 'k8s-processor/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/k8s-processor:${{ github.sha }} ./k8s-processor
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/k8s-processor:${{ github.sha }}
